version: '3.8'

services:

  ms_boletas:
    build:
      context: ./ms_boletas
    environment:
      - STAGE=${STAGE}
    volumes:
      - ~/.aws:/root/.aws
      - /home/ubuntu/logs:/app/logs


  ms_descuentos:
    build:
      context: ./ms_descuentos
    environment:
      - STAGE=${STAGE}
    volumes:
      - ~/.aws:/root/.aws
      - /home/ubuntu/logs:/app/logs


  ms_encuestas:
    build:
      context: ./ms_encuestas
    environment:
      - STAGE=${STAGE}
    volumes:
      - ~/.aws:/root/.aws
      - /home/ubuntu/logs:/app/logs


  ms_estudiantes:
    build:
      context: ./ms_estudiantes
    environment:
      - STAGE=${STAGE}
    volumes:
      - ~/.aws:/root/.aws
      - /home/ubuntu/logs:/app/logs


  ms_inscripciones:
    build:
      context: ./ms_inscripciones
    environment:
      - STAGE=${STAGE}
    volumes:
      - ~/.aws:/root/.aws
      - /home/ubuntu/logs:/app/logs


  ms_programas:
    build:
      context: ./ms_programas
    environment:
      - STAGE=${STAGE}
    volumes:
      - ~/.aws:/root/.aws
      - /home/ubuntu/logs:/app/logs


